{
  pkgs,
  lib,
  config,
  ...
}:
{
  boot = {
    # kernel console loglevel
    consoleLogLevel = 3;

    # settings shared between bootloaders
    loader = {
      # whether to copy the necessary boot files into /boot
      # so that /nix/store is not needed by the boot loader.
      generationsDir.copyKernels = true;

      # allow installation to modify EFI variables
      efi.canTouchEfiVariables = true;
    };

    # instructions on how /tmp should be handled
    # if your system is low on ram, you should avoid tmpfs to prevent hangups while compiling
    tmp = {
      # /tmp on tmpfs, lets it live on your ram
      # it defaults to FALSE, which means you will use disk space instead of ram
      # enable tmpfs tmp on anything except servers and builders
      useTmpfs = true;

      # If not using tmpfs, which is naturally purged on reboot, we must clean
      # /tmp ourselves. /tmp should be volatile storage!
      cleanOnBoot = lib.mkDefault (!config.boot.tmp.useTmpfs);
    };

    initrd = {
      # Verbosity of the initrd
      # disabling verbosity removes only the mandatory messages generated by the NixOS
      verbose = false;

      systemd = {
        # enable systemd in initrd
        enable = true;

        # packages that will be added to the PATH in initrd
        # this is useful for debugging if the host provides
        # emergency access
        storePaths = with pkgs; [
          util-linux
          pciutils
        ];
        extraBin = {
          fdisk = "${pkgs.util-linux}/bin/fdisk";
          lsblk = "${pkgs.util-linux}/bin/lsblk";
          lspci = "${pkgs.pciutils}/bin/lspci";
        };
      };

      # List of modules that are always loaded by the initrd
      kernelModules = [
        "ahci"
        "nvme"
        "xhci_pci"
        "btrfs"
        "sd_mod"
        "dm_mod"
        "tpm"
      ];

      # the set of kernel modules in the initial ramdisk used during the boot process
      availableKernelModules = [
        "usbhid"
        "sd_mod"
        "sr_mod"
        "dm_mod"
        "uas"
        "usb_storage"
        "rtsx_usb_sdmmc"
        "rtsx_pci_sdmmc" # Realtek PCI-Express SD/MMC Card Interface driver
        "ata_piix"
        "virtio_pci"
        "virtio_scsi"
        "ehci_pci"
      ];
    };

    kernelParams = [
      # https://en.wikipedia.org/wiki/Kernel_page-table_isolation
      # auto means kernel will automatically decide the pti state
      "pti=auto" # on | off

      # CPU idle behaviour
      #  poll: slightly improve performance at cost of a hotter system (not recommended)
      #  halt: halt is forced to be used for CPU idle
      #  nomwait: Disable mwait for CPU C-states
      "idle=nomwait" # poll | halt | nomwait

      # disable usb autosuspend
      "usbcore.autosuspend=-1"

      # disables resume and restores original swap space
      "noresume"

      # allows systemd to set and save the backlight state
      "acpi_backlight=native" # none | vendor | video | native

      # prevent the kernel from blanking plymouth out of the fb
      "fbcon=nodefer"

      # disable the cursor in vt to get a black screen during intermissions
      "vt.global_cursor_default=0"

      # disable displaying of the built-in Linux logo
      "logo.nologo"
    ];
  };
}
