files.extend-exclude = [
  "flake.lock",
  "**/Cargo.lock",
  "secrets/**",
  ".git/**",
  ".opencode/node_modules/**",
]

[default.extend-words]
ags = "ags"
Calculater = "Calculater"
Certificacion = "Certificacion"
CROS = "CROS"
HDA = "HDA"
extens = "extens"
imput = "imput"
nd = "nd"
