{
  inputs,
  pkgs,
  lib,
  config,
  self,
  system,
  ...
}:
let
  inherit (pkgs.stdenv.hostPlatform) isDarwin;

  spicePkgs = inputs.spicetify-nix.legacyPackages.${system};
  spicetifyCliSource = pkgs.fetchzip {
    url = "https://github.com/spicetify/cli/archive/refs/tags/v2.44.0.tar.gz";
    hash = "sha256-4RRy1mmqjKxDUqSV7W6KHZZcbsJvnB2hZpys1MPip3E=";
    stripRoot = true;
  };
  spicetifyPackage = pkgs.spicetify-cli.overrideAttrs (old: {
    nativeBuildInputs = (old.nativeBuildInputs or [ ]) ++ [ pkgs.esbuild ];

    # spicetify-cli looks up this generated helper next to the executable at
    # runtime. The nixpkgs package currently omits it, which leaves the app
    # with a black xpui page after Spicetify injects helper/spicetifyWrapper.js.
    postInstall = (old.postInstall or "") + ''
      mkdir -p "$out/share/spicetify/jsHelper"
      chmod u+w "$out/share/spicetify/jsHelper"
      esbuild \
        --banner:js="/* Generated by scripts/build-wrapper.mjs. Do not edit directly. */" \
        --bundle "${spicetifyCliSource}/src/jsHelper/spicetifyWrapper/index.js" \
        --format=iife \
        --legal-comments=none \
        --log-level=warning \
        --minify \
        --outfile="$out/share/spicetify/jsHelper/spicetifyWrapper.js" \
        --sourcemap \
        --target=chrome108
    '';
  });
  spotifyPackage = if isDarwin then self.packages.${system}.spotify-spotx else pkgs.spotify;
  spotifyEntitlements = ../../pkgs/spotify-spotx/entitlements.plist;

  spotifyDarwinInstallDir = "${config.home.homeDirectory}/${config.targets.darwin.copyApps.directory}";
  spotifyDarwinApp = "${spotifyDarwinInstallDir}/Spotify.app";
in
{
  imports = [ inputs.spicetify-nix.homeManagerModules.default ];

  # Keep macOS Spotify stable by removing pending auto-updates and stale patch
  # artifacts without touching user data, login state, playlists, or downloads.
  home.activation.cleanupSpotifyDarwinState = lib.mkIf isDarwin (
    lib.hm.dag.entryBefore [ "copyApps" ] ''
      spotifyStateDir="${config.home.homeDirectory}/Library/Application Support/Spotify"
      persistentCacheDir="$spotifyStateDir/PersistentCache"
      updatePath="$persistentCacheDir/Update"

      rm -rf \
        "${config.home.homeDirectory}/Library/Caches/com.spotify.client" \
        "${config.home.homeDirectory}/Library/Saved Application State/com.spotify.client.savedState"

      if [ -e "$updatePath" ]; then
        rm -rf "$updatePath"
      fi
      mkdir -p "$updatePath"
      chmod 500 "$updatePath" 2>/dev/null || true

      for appPath in \
        "${spotifyDarwinApp}"
      do
        resourcesPath="$appPath/Contents/Resources"
        appsPath="$resourcesPath/Apps"

        if [ -d "$appsPath" ]; then
          rm -rf \
            "$appsPath/xpui" \
            "$appsPath/xpui.bak" \
            "$appsPath/xpui.spa.bak"
        fi

        if [ -d "$resourcesPath" ]; then
          rm -rf \
            "$resourcesPath/Backup" \
            "$resourcesPath/.spicetify"
        fi
      done

      if [ -d "${config.home.homeDirectory}/.config/spicetify/Backup" ]; then
        rm -rf "${config.home.homeDirectory}/.config/spicetify/Backup"
      fi
    ''
  );

  # Nixpkgs' sandbox-friendly darwin.sigtool signs Mach-O files in the package,
  # but Spotify's CEF bundle also needs a full app resource envelope after
  # Home Manager copies the app out of the immutable store.
  home.activation.repairSpotifyDarwinAppSignature = lib.mkIf isDarwin (
    lib.hm.dag.entryAfter [ "copyApps" ] ''
      spotifyApp="${spotifyDarwinApp}"

      if [ -d "$spotifyApp" ]; then
        /usr/bin/xattr -cr "$spotifyApp" 2>/dev/null || true
        /usr/bin/codesign --force --deep --options runtime --entitlements "${spotifyEntitlements}" --sign - "$spotifyApp"
        /usr/bin/codesign --verify --deep --strict --verbose=2 "$spotifyApp"
      fi
    ''
  );

  programs.spicetify = {
    enable = true;
    inherit spotifyPackage;
    inherit spicetifyPackage;

    # theme = lib.mkForce comfyTheme;
    # colorScheme = lib.mkForce "Spotify";
    theme = lib.mkForce {
      name = "";
      src = ./.;
    };
    colorScheme = lib.mkForce "";

    enabledExtensions = with spicePkgs.extensions; [
      adblock
      volumePercentage
      shuffle
      copyLyrics
      fullAlbumDate
    ];
  };
}
